### ISSUE TITLE
Firebase Auth Config Error

### ISSUE THREAD

**Issue by bittrama** [gheorghedarle/Xamarin-ToDoApp#1]
Hello, I was running your app but the Firebase is not working fine. I created the project and downloaded the google-services.json into the Android project. 
![Error](https://user-images.githubusercontent.com/54611392/148823344-889951ec-10ce-43bc-b9a1-5ff9880e4270.PNG)

**Comment by gheorghedarle** [comment]
Hello @bittrama, 
I've checked and it works fine for me, also I've fixed a small validation issue related to registration in the latest commit.
Can you please check that in your firebase console the **Email/Password** provider is **Enabled** (You can find this configuration in firebase console Build->Authentication->Sign-in Method)

**Comment by bittrama** [comment]
Excellent, it is working fine now !... thanks ! Excellent sample App :)
