### ISSUE TITLE
App Crash & Forgot Password is Missing

### ISSUE THREAD

**Issue by MohitNegi93** [gheorghedarle/Xamarin-ToDoApp#2]
Hey! App is very beautiful but there is bug first of all app is crash when i click on setting and select Displasy Tasks from that time application is crash. And one more thing forgot password is missing.

**Comment by gheorghedarle** [comment]
Hello @MohitNegi93,
I've fixed the issue regarding display tasks in the latest commit, thanks for letting me know. 
I will implement the **Forgot Passcode** functionality as soon as possible.

**Comment by gheorghedarle** [comment]
I've added the **Forgot Password** functionality.
I will close the issue.
