### ISSUE TITLE
Any plans to transform X-ToDo into MS ToDo? 

### ISSUE THREAD

**Issue by mediaexplorer74** [gheorghedarle/Xamarin-ToDoApp#5]
Hi! Nice App (but incompatible with .NET Standard 1.4, heh).
Do you have any plans to transform X-ToDo into MS ToDo? 
My dream is to recover MS TODO on old sweet Lumia 950 ( Microsoft switched off OneDrive sync for its old UWP app.)
MS Graph API (and Tasks api in particular case) is the open tech. :)
I made some draft MS Todo app.... but it has no UI :)

**Comment by gheorghedarle** [comment]
@mediaexplorer74 No, unfortunately, I don't have any plans to transform the app into MS ToDo in the near future. But I will consider it.
