### ISSUE TITLE
Please help me to fix UWP project at my fork of your great multi-platform solution

### ISSUE THREAD

**Issue by mediaexplorer74** [gheorghedarle/Xamarin-ToDoApp#6]
Hi! How are you?
Do you have some Windows notebook/Tablet? Or, perhaps, some old sweet Lumia phone with Windows (10 mobile)? ;) 
Please add UWP project into your XamarinForms solution if you can ... and your ToDo will be great app )
Oh, plus Microsoft Todo API (Microsoft Graph) :)
Cheers up,
m.e.
Update: new theme of my issue. Please see the item number 3 for details

**Comment by gheorghedarle** [comment]
Hello, I will try to add the UWP project to the solution in the near future.

**Comment by mediaexplorer74** [comment]
> Hello, I will try to add the UWP project to the solution in the near future.

Hello,
I forked your Xamarin-ToDoApp: https://github.com/mediaexplorer74/Xamarin-ToDoApp
UWP target added. Bad news: Xamarin.Auth for UWP not found...  https://github.com/xamarin/GooglePlayServicesComponents obsolete (or UWP obsolete, idk).
Help to continue "migration" to UWP if you can..... You're cool C# developer, instead of me ) IMHO

P.S. Also I forked WeatherApp... UWP version works fifty-fifty (UI transforms at strange design.. a little))
P.P.S. I started to reanimate obsolete MS Todo... 1st proto ready for now
